### ISSUE TITLE
cobrapy load

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/standard-GEM-validation#2]
The pipeline should check that the model is successfully imported by `cobrapy` via all compatible formats that exist on the `main` branch:

- [x] YAML
- [x] SBML
- [x] Matlab
- [x] JSON

**Comment by famosab** [comment]
It might make more sense to use the `cobra.io.sbml.validate_sbml_model` function to test whether a model is valid SBML. 

I think in general the SBML format should be the preferred format to test the models (it is the community standard in my eyes), testing the model in other formats is still desirable though.

Would it make sense to add a model comparison which determines if all the models stored in different formats describe the same thing?

**Comment by mihai-sysbio** [comment]
> It might make more sense to use the `cobra.io.sbml.validate_sbml_model` function to test whether a model is valid SBML.

Very nice suggestion @famosab. It has been implemented through 2760ca2fe82cf9269f1a06f145189d8f7921019c.

> Would it make sense to add a model comparison which determines if all the models stored in different formats describe the same thing?

Actually I'm not sure. SBML is the most comprehensive model format, so it might be that no other format quite matches it. What formats were you thinking of?

**Comment by famosab** [comment]
Yes I would agree that XML files in SBML format should be used. In a couple of the example repositories that are being validated here, I saw that models were also present in `yml` or `mat` (for example [Human-GEM](https://github.com/MetabolicAtlas/Human-GEM/tree/master/model). I was just unsure how and if we should handle these kinds of files as well. We could ignore them and just argue that SBML format is the community standard and thus whats being tested within our validation setup.
